version: "3"
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    container_name: es01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.search.max_buckets=50000
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /mnt/n01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    container_name: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.search.max_buckets=50000
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /mnt/n02:/usr/share/elasticsearch/data
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    container_name: es03
    environment:
      - node.name=es03
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.search.max_buckets=50000
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /mnt/n03:/usr/share/elasticsearch/data
  graphql:
    container_name: graphql
    image: shahcompbio/spectrum-scrna-graphql
    environment:
      - HOST=es01
    depends_on:
      - es01
      - es02
      - es03
  frontend:
    container_name: frontend
    image: shahcompbio/spectrum-scrna-react
    ports:
      - "80:80"
    depends_on:
      - graphql
